PREFIX changes-graph: <http://www.example.com/changesGraph/user/>
PREFIX notification-graph: <http://www.example.com/notificationGraph/user/>
PREFIX contact-graph: <http://www.example.com/contactDetailsGraph/user/>
PREFIX cdo: <https://change-detection-ontology.adaptcentre.ie/#>
PREFIX rei-constraint: <http://www.cs.umbc.edu/~lkagal1/rei/ontologies/ReiConstraint.owl#>
PREFIX rei-policy: <http://www.cs.umbc.edu/~lkagal1/rei/ontologies/ReiPolicy.owl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


SELECT ?changeType ?threshold
WHERE
{
  # QUERY NOTIFICATION GRAPH
  GRAPH notification-graph:1  {
    # GET THRESHOLD FOR EACH CHANGE TYPE
    ?constraint a rei-constraint:SimpleConstraint;
       rei-constraint:subject ?changeType;
       rei-constraint:object ?threshold .
  }
}
